version: '3' # composeファイルのバージョン
services:
  boiler-plate: # サービス名
    container_name: boiler-plate
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    volumes: # マウントディレクトリ
      - ./go-sample:/go/src/go-sample
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
