version: '3' # composeファイルのバージョン
services:
  app: # サービス名
    container_name: go-sample
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./Dockerfile
    tty: true # コンテナの永続化
    ports:
      - "8080:8080"
    env_file: # .envファイル
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
    command: ./start.sh